package org.bukkit;

public enum Sound {
    BLOCK_BELL_USE,
    BLOCK_BEACON_ACTIVATE,
    BLOCK_CHEST_CLOSE,
    BLOCK_NOTE_BLOCK_BELL,
    BLOCK_NOTE_BLOCK_PLING,
    BLOCK_SNOW_BREAK,
    ENTITY_DRAGON_FIREBALL_EXPLODE,
    ENTITY_ENDER_DRAGON_GROWL,
    ENTITY_ENDER_DRAGON_DEATH,
    ENTITY_FIREWORK_ROCKET_LAUNCH,
    ENTITY_FIREWORK_ROCKET_TWINKLE,
    ENTITY_GENERIC_EXPLODE,
    ENTITY_EXPERIENCE_ORB_PICKUP,
    ENTITY_PLAYER_LEVELUP,
    ITEM_FIRECHARGE_USE,
    ITEM_TOTEM_USE,
    UI_TOAST_CHALLENGE_COMPLETE
}
