package nl.mitchsmp.core.util;

import org.bukkit.ChatColor;
import org.bukkit.command.CommandSender;

public final class Text {
    private static final String[][] VISIBLE_TEXT_REPLACEMENTS = {
            {"MitchSMP", "BloodboundSMP"},
            {"Mitch SMP", "BloodboundSMP"},
            {"Gamemode van", "Gamemode for"},
            {"Rank van", "Rank for"},
            {"Hearts van", "Hearts for"},
            {"Admin balance van", "Admin balance for"},
            {"Tijd gezet naar", "Time set to"},
            {"Shop teruggezet naar defaults.", "Shop reset to defaults."},
            {"gezet naar", "set to"},
            {"teruggezet", "reset"},
            {"Geteleporteerd naar", "Teleported to"},
            {"geteleporteerd naar", "teleported to"},
            {"Geen permissie.", "You do not have permission."},
            {"Alleen players.", "Players only."},
            {"Alleen spelers.", "Players only."},
            {"Geen arena.", "No arena."},
            {"Speler niet online.", "Player is not online."},
            {"Speler niet gevonden.", "Player not found."},
            {"Geen speler gevonden.", "No player found."},
            {"Gebruik:", "Usage:"},
            {"Gebruik ", "Use "},
            {"Onbekende setting.", "Unknown setting."},
            {"Onbekende key.", "Unknown key."},
            {"Onbekende mode.", "Unknown mode."},
            {"Onbekende actie.", "Unknown action."},
            {"Onbekende ability.", "Unknown ability."},
            {"Onbekende category.", "Unknown category."},
            {"Onbekende emote.", "Unknown emote."},
            {"Onbekend onderdeel.", "Unknown component."},
            {"Ongeldige prijs.", "Invalid price."},
            {"Ongeldig bedrag.", "Invalid amount."},
            {"Ongeldige value.", "Invalid value."},
            {"Prijs moet een nummer zijn.", "Price must be a number."},
            {"Value moet een nummer zijn.", "Value must be a number."},
            {"Minuten moet een nummer zijn.", "Minutes must be a number."},
            {"Bevestig met:", "Confirm with:"},
            {"Huidig: geen", "Current: none"},
            {"Huidig:", "Current:"},
            {"Actief:", "Active:"},
            {"Onderdelen:", "Components:"},
            {"Spelers:", "Players:"},
            {"Nog niemand", "No one yet"},
            {"nog niemand", "no one yet"},
            {"nog niet gestart", "not started yet"},
            {"Je bent nog gemute.", "You are still muted."},
            {"Je bent gemute voor", "You have been muted for"},
            {"Speler gemute.", "Player muted."},
            {"Speler unmuted.", "Player unmuted."},
            {"minuten", "minutes"},
            {"seconden", "seconds"},
            {"dagen", "days"},
            {"Je bent nu in combat. Geen /home, /tpa of logout.", "You are now in combat. No /home, /tpa, or logging out."},
            {"Je bent niet in combat.", "You are not in combat."},
            {"logde uit tijdens combat en stierf.", "logged out during combat and died."},
            {"Corrupted Hearts zijn uitgeschakeld in BedWars.", "Corrupted Hearts are disabled in BedWars."},
            {"Je Corrupted Heart herstelde 1 heart. Je hebt nu", "Your Corrupted Heart restored 1 heart. You now have"},
            {"Corrupted Heart gegeven.", "Corrupted Heart granted."},
            {"Zeldzaam gevonden in oude kisten.", "Rarely found in ancient chests."},
            {"Onbekende key. Gebruik tab-complete.", "Unknown key. Use tab completion."},
            {"Je verloor 1 heart. Je hebt nu", "You lost 1 heart. You now have"},
            {"Je kreeg 1 heart. Je hebt nu", "You gained 1 heart. You now have"},
            {"Geen heart gain:", "No heart gain:"},
            {"Geen open TPA verzoek.", "No open TPA request."},
            {"Je TPA verzoek is geweigerd.", "Your TPA request was denied."},
            {"Je bent geteleporteerd.", "You have been teleported."},
            {"Admin mode aan.", "Admin mode enabled."},
            {"Je bent al in admin mode.", "You are already in admin mode."},
            {"Je bent niet in admin mode.", "You are not in admin mode."},
            {"Admin actie uitgevoerd.", "Admin action executed."},
            {"Admin mode items kun je niet droppen. Drop is gewist.", "Admin mode items cannot be dropped. Drop erased."},
            {"Je kunt geen commands gebruiken vanuit jail.", "Commands are disabled while jailed."},
            {"Possession gestopt omdat de entity niet meer geldig is.", "Possession stopped because the entity is no longer valid."},
            {"Je zit in jail.", "You are jailed."},
            {"Deze jail area is protected.", "This jail area is protected."},
            {"No-clip aan.", "No-clip enabled."},
            {"No-clip uit.", "No-clip disabled."},
            {"No-clip getoggled for", "No-clip toggled for"},
            {"Klik op een mob/entity om drive-possession te starten.", "Click a mob/entity to start possession."},
            {"Terug geteleporteerd.", "Teleported back."},
            {"Coordinaten ongeldig.", "Invalid coordinates."},
            {"is naar jou geteleporteerd.", "was teleported to you."},
            {"Inventory geleegd van", "Inventory cleared for"},
            {"Ancient Debris bait kan alleen in de Nether gekozen worden.", "Ancient Debris bait can only be selected in the Nether."},
            {"Fake ore select mode:", "Fake ore selection mode:"},
            {"Rechtsklik blokken om 2x2x2 bait veins te plaatsen.", "Right-click blocks to place 2x2x2 bait veins."},
            {"stopt.", "stops."},
            {"Fake vein geplaatst:", "Fake vein placed:"},
            {"target(s)", "target(s)"},
            {"Niet bedoeld als normale economy reward.", "Not intended as a normal economy reward."},
            {"Freeze uit for", "Freeze disabled for"},
            {"Freeze aan for", "Freeze enabled for"},
            {"Je bent niet meer frozen.", "You are no longer frozen."},
            {"Je bent gefreezed door staff. Log niet uit.", "You were frozen by staff. Do not log out."},
            {"Lockdown actief for", "Lockdown active for"},
            {"Release uitgevoerd for", "Release executed for"},
            {"Staff lockdown/freeze is opgeheven.", "Staff lockdown/freeze has been lifted."},
            {"Deze speler zit niet in jail.", "This player is not jailed."},
            {"Je kijkt nu from buiten de cel van", "You are now watching the cell of"},
            {"is uit jail gehaald.", "has been released from jail."},
            {"Je moet in staffmode zijn for een staff PvP test.", "You must be in staff mode for a staff PvP test."},
            {"Je kunt geen PvP request naar jezelf sturen.", "You cannot send a PvP request to yourself."},
            {"Target zit zelf in staffmode. Zet eerst een van beide uit of gebruik een normale speler.", "The target is in staff mode. Disable one staff mode first or use a normal player."},
            {"Staff PvP request gestuurd naar", "Staff PvP request sent to"},
            {"Geldig for 60 seconden.", "Valid for 60 seconds."},
            {"wil tijdelijk PvP met jou testen.", "wants to temporarily test PvP with you."},
            {"Accepteer met", "Accept with"},
            {"of weiger met", "or deny with"},
            {"Staff PvP sessie gestopt.", "Staff PvP session stopped."},
            {"Je hebt geen actieve staff PvP sessie.", "You have no active staff PvP session."},
            {"Je hebt geen actieve staff PvP aanvraag.", "You have no active staff PvP request."},
            {"De staff PvP aanvraag is verlopen.", "The staff PvP request expired."},
            {"Staff PvP aanvraag geweigerd.", "Staff PvP request denied."},
            {"weigerde je staff PvP aanvraag.", "denied your staff PvP request."},
            {"Staff PvP met", "Staff PvP with"},
            {"Stop met", "Stop with"},
            {"accepteerde. PvP tussen jullie is allowed for 10 minutes.", "accepted. PvP between you is allowed for 10 minutes."},
            {"Staff PvP sessie is verlopen.", "Staff PvP session expired."},
            {"Staff PvP sessie met", "Staff PvP session with"},
            {"is gestopt.", "has stopped."},
            {"Vanish aan.", "Vanish enabled."},
            {"Vanish uit.", "Vanish disabled."},
            {"Je hebt je starter kit al geclaimd.", "You already claimed your starter kit."},
            {"Unknowne shop tab.", "Unknown shop tab."},
            {"Maak hem met", "Create it with"},
            {"Price moet hoger zijn dan 0.", "Price must be higher than 0."},
            {"Shop edit geopend. Klik een slot met het item in je hand.", "Shop editor opened. Click a slot with the item in your hand."},
            {"Bekijk items:", "View items:"},
            {"Je zit in testwereld", "You are in test world"},
            {"toon sandboxes", "show sandboxes"},
            {"ga naar sandbox met losse inventory", "go to a sandbox with isolated inventory"},
            {"reset sandbox volledig", "fully reset sandbox"},
            {"Wacht nog", "Wait another"},
            {"voor RTP.", "before using RTP."},
            {"Nieuwe season gestart voor", "New season started for"},
            {"Huidige King:", "Current King:"},
            {"Geen oude seasons gevonden.", "No old seasons found."},
            {"Seasonal stats zijn gereset en Progression overall reset is aangeroepen.", "Seasonal stats were reset and the progression overall reset was triggered."},
            {"is verwijderd uit season-data en HOF.", "was removed from season data and the Hall of Fame."},
            {"Geen tekstrecord gevonden, maar visuele HOF delete is geprobeerd voor season", "No text record was found, but the visual Hall of Fame deletion was attempted for season"},
            {"Je draagt nu de gouden tag", "You now carry the golden tag"},
            {"HUD aangezet.", "HUD enabled."},
            {"HUD uitgezet.", "HUD disabled."},
            {"HUD gereset.", "HUD reset."},
            {"Onbekende mode. Gebruik seasonal of overall.", "Unknown mode. Use seasonal or overall."},
            {"Onbekend onderdeel. Gebruik /hud list.", "Unknown component. Use /hud list."},
            {"Dit opent de Infernal Sovereign ritual en consumeert je ritueel-items.", "This opens the Infernal Sovereign ritual and consumes your ritual items."},
            {"Na het starten kan niemand uit de hell-wereld ontsnappen met commands.", "After it starts, nobody can escape the hell world with commands."},
            {"Er is al een ritual party. Gebruik /endboss join.", "A ritual party already exists. Use /endboss join."},
            {"Er loopt al een bossfight.", "A boss fight is already running."},
            {"Je zit al in de ritual party.", "You are already in the ritual party."},
            {"Je staat op het punt een one-way endgame bossfight te joinen.", "You are about to join a one-way endgame boss fight."},
            {"Na start kun je niet weg met /home, /spawn, /back, /tpa of vergelijkbare commands.", "After the fight starts, /home, /spawn, /back, /tpa and similar commands are disabled."},
            {"Geen actieve bevestiging. Gebruik /endboss start of /endboss join opnieuw.", "No active confirmation. Use /endboss start or /endboss join again."},
            {"opende de Infernal Sovereign ritual. Gebruik", "opened the Infernal Sovereign ritual. Use"},
            {"om mee te gaan.", "to join."},
            {"Ritual party geopend.", "Ritual party opened."},
            {"joined de ritual party.", "joined the ritual party."},
            {"Geen actieve endboss ritual.", "No active endboss ritual."},
            {"Geen ritual party om te starten.", "No ritual party to start."},
            {"Endboss force-start uitgevoerd.", "Endboss force-start executed."},
            {"Gebruik een positief getal.", "Use a positive number."},
            {"Endboss config aangepast:", "Endboss config updated:"},
            {"Je bent uit de bossfight gevallen.", "You fell out of the boss fight."},
            {"Je zit vast in de bossfight. Win, sterf, of wacht tot de party wiped.", "You are trapped in the boss fight. Win, die, or wait until the party wipes."},
            {"hearts nodig om dit ritual te openen.", "hearts to open this ritual."},
            {"Je mist:", "Missing:"},
            {"Boss charged attacks kunnen je niet one-shotten.", "Boss charged attacks cannot one-shot you."},
            {"Bewijs dat je de hell fight hebt overleefd.", "Proof that you survived the hell fight."},
            {"Geen Spleef arenas.", "No Spleef arenas."},
            {"Commands zijn uit tijdens Spleef.", "Commands are disabled during Spleef."},
            {"Wacht tot de ronde start.", "Wait for the round to start."},
            {"Gebruik snowballs om de vloer weg te schieten.", "Use snowballs to shoot out the floor."},
            {"Je zit al in Spleef.", "You are already in Spleef."},
            {"Je zit niet in Spleef.", "You are not in Spleef."},
            {"Je bent uitgeschakeld.", "You have been eliminated."},
            {"Spleef eindigde zonder winnaar.", "Spleef ended without a winner."},
            {"Spleef winnaar:", "Spleef winner:"},
            {"Geen TNT Run arenas.", "No TNT Run arenas."},
            {"Je zit in TNT Run.", "You joined TNT Run."},
            {"Je zit niet in TNT Run.", "You are not in TNT Run."},
            {"TNT Run eindigde zonder winnaar.", "TNT Run ended without a winner."},
            {"Je staat terug in de TNT Run lobby.", "You are back in the TNT Run lobby."},
            {"Geen BedWars arenas.", "No BedWars arenas."},
            {"Je zit al in BedWars.", "You are already in BedWars."},
            {"Je zit niet in BedWars.", "You are not in BedWars."},
            {"Je bent terug naar survival.", "You returned to survival."},
            {"Je survival inventory is hersteld na een BedWars/server restart.", "Your survival inventory was restored after a BedWars/server restart."},
            {"Niet genoeg spelers in deze arena. Nodig:", "Not enough players in this arena. Required:"},
            {"Start-countdown gestart voor", "Start countdown started for"},
            {"Je bed leeft nog, je respawnt bij je eiland.", "Your bed is still alive. Respawning at your island."},
            {"Je kunt je eigen bed niet breken.", "You cannot break your own bed."},
            {"Je kunt geen blok in een levend bed plaatsen.", "You cannot place blocks inside an active bed."},
            {"Alleen bouwblokken uit BedWars mogen geplaatst worden.", "Only BedWars build blocks may be placed."},
            {"Je speelt als team", "You are playing as team"},
            {"Je staat terug in de BedWars lobby. Volgende ronde start automatisch.", "You are back in the BedWars lobby. The next round starts automatically."},
            {"Je blijft in de BedWars lobby tot de match start.", "Stay in the BedWars lobby until the match starts."},
            {"Je won de BedWars pot:", "You won the BedWars pot:"},
            {"Niet genoeg geld voor deze pot.", "Not enough money for this pot."},
            {"Gekocht:", "Purchased:"},
            {"Verkocht:", "Sold:"},
            {"Bounty niet uitbetaald:", "Bounty not paid:"},
            {"Je claimde een bounty van", "You claimed a bounty of"},
            {"Geen verdachte spelers gelogd.", "No suspicious players logged."},
            {"Geen sus-data voor deze speler.", "No suspicion data for this player."},
            {"AntiCheat alerts staan aan voor Moderator+ en audit owner.", "AntiCheat alerts are enabled for Moderator+ and the audit owner."},
            {"voor verdachte spelers", "for suspicious players"},
            {"Verdachte spelers", "Suspicious players"},
            {"Laatste check", "Last check"},
            {"Laatste alerts", "Latest alerts"},
            {"Geen listings gevonden", "No listings found"},
            {"Listing niet gevonden.", "Listing not found."},
            {"Listing gekocht voor", "Listing purchased for"},
            {"Je kunt je eigen listing niet kopen.", "You cannot buy your own listing."},
            {"Je hebt niet genoeg geld.", "You do not have enough money."},
            {"Je hebt je AH listing limiet bereikt:", "You reached your AH listing limit:"},
            {"Je AH listing limiet is bereikt:", "Your AH listing limit has been reached:"},
            {"Nieuwe listing", "New listing"},
            {"Mijn listings", "My listings"},
            {"Gesloten listing slot", "Locked listing slot"},
            {"Upgrade je rank voor meer AH slots.", "Upgrade your rank for more AH slots."},
            {"Vorige pagina", "Previous page"},
            {"Volgende pagina", "Next page"},
            {"Geen vorige pagina", "No previous page"},
            {"Geen volgende pagina", "No next page"},
            {"Klik om terug te gaan.", "Click to go back."},
            {"Klik om verder te gaan.", "Click to continue."},
            {"Klik om te togglen.", "Click to toggle."},
            {"Klik om te kopen.", "Click to buy."},
            {"Terug naar AH", "Back to AH"},
            {"Open het hoofdmenu.", "Open the main menu."},
            {"Zoeken", "Search"},
            {"Zoeken geannuleerd.", "Search cancelled."},
            {"Zoeken gewist.", "Search cleared."},
            {"Zoeken naar", "Searching for"},
            {"Sorteer", "Sort"},
            {"Prijs", "Price"},
            {"regel 1", "line 1"},
            {"Typ je zoekterm op regel 1 van het bord en klik Done.", "Type your search term on line 1 of the sign and click Done."},
            {"Kon sign input niet openen.", "Could not open sign input."},
            {"Gebruik tijdelijk", "Temporarily use"},
            {"Item teruggegeven.", "Item returned."},
            {"Pas je zoekfilter aan.", "Adjust your search filter."},
            {"Plaatsen:", "List:"},
            {"Plaats een item op dit vrije slot om een listing te maken.", "Place an item on this free slot to create a listing."},
            {"Klik een item uit je inventory of plaats een cursor-item op een vrij AH-slot.", "Click an item in your inventory or place a cursor item onto a free AH slot."},
            {"Dit guide boek kan niet verkocht worden.", "This guide book cannot be sold."},
            {"QuickSell niet gebruiken in adminmode, creative/spectator, BedWars of testworld.", "You cannot use QuickSell in admin mode, creative/spectator, BedWars, or the test world."},
            {"Sleep alles wat je wilt verkopen naar het QuickSell venster en klik bevestigen.", "Drag everything you want to sell into the QuickSell window and click confirm."},
            {"Sleep je hand-item naar het QuickSell venster en klik bevestigen.", "Drag the item in your hand into the QuickSell window and click confirm."},
            {"Je hand is leeg of niet verkoopbaar.", "Your hand is empty or not sellable."},
            {"Annuleer", "Cancel"},
            {"Bevestig verkoop", "Confirm sale"},
            {"Prijsinfo", "Price info"},
            {"Niet verkoopbaar.", "Not sellable."},
            {"Je hebt geen verkoopbare items in je inventory.", "You have no sellable items in your inventory."},
            {"Sleep items uit je inventory naar boven.", "Drag items from your inventory into the top area."},
            {"Sluit QuickSell en geeft alle items terug.", "Close QuickSell and return all items."},
            {"Klik voor de prijzen van je huidige inventory.", "Click for prices in your current inventory."},
            {"Hover items voor waarde per stuk en per stack.", "Hover items for value per item and per stack."},
            {"Je betaalde", "You paid"},
            {"Je kreeg", "You received"},
            {"Tag uitgezet.", "Tag disabled."},
            {"Boss Shards gegeven.", "Boss Shards granted."},
            {"Drop zeldzaam van bosses.", "Rare drop from bosses."},
            {"Gebruik ze hier voor OP items.", "Use them here for endgame items."},
            {"Je hebt &f", "You need &f"},
            {"Boss Shards nodig.", "Boss Shards."},
            {"De Phoenix Totem verblindt je door de explosie!", "The Phoenix Totem blinds you through the blast!"},
            {"Phoenix Totem geactiveerd: je bent herboren in vuur.", "Phoenix Totem activated: you are reborn in fire."},
            {"Extreem zeldzame boss currency.", "Extremely rare boss currency."}
    };
    public static final String PREFIX = color("&8[&4Bloodbound&8] &7");

    private Text() {
    }

    public static String color(String input) {
        return ChatColor.translateAlternateColorCodes('&', brand(input == null ? "" : input));
    }

    public static String rawColor(String input) {
        return ChatColor.translateAlternateColorCodes('&', input == null ? "" : input);
    }

    private static String brand(String input) {
        String output = input;
        for (String[] replacement : VISIBLE_TEXT_REPLACEMENTS) {
            output = output.replace(replacement[0], replacement[1]);
        }
        return output;
    }

    public static void msg(CommandSender sender, String message) {
        sender.sendMessage(PREFIX + color(message));
    }

    public static String stripColorCodes(String input) {
        return ChatColor.stripColor(color(input == null ? "" : input));
    }
}

