name: MitchSMP-Safezones
version: 0.1.0
main: nl.mitchsmp.safezones.SafezonesPlugin
api-version: '1.21'
depend: [MitchSMP-Core]
commands:
  safezone:
    description: Manage Bloodbound safezones
    usage: /safezone
    aliases: [sz]
  commandsign:
    description: Bind a command to a protected sign.
    usage: /commandsign <set|text|remove|info>
    aliases: [csign]
permissions:
  mitchsmp.safezones.admin:
    description: Manage safezones
    default: op
